package dittonut.darkskin;

import static dittonut.darkskin.DarkSkin.mm;

import org.bukkit.Color;
import org.bukkit.Material;
import org.bukkit.NamespacedKey;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.inventory.meta.PotionMeta;
import org.bukkit.potion.PotionEffect;
import org.bukkit.potion.PotionEffectType;

import net.kyori.adventure.text.Component;

public class Enums {
    // TODO: make private ItemStacks and methods only clone and return them. Item is generated by static block
    // TODO: needs to be finalized
    public static Component ENCHANT_GUI_TITLE = mm.deserialize("<#F40001><reset>마법 부여");
    public static Component PYLON_GUI_TITLE = mm.deserialize("<#F40002><reset>파일런");
    public static int MAX_ENCHANTMENTS = 10;
    public static int ENCHANT_ADD_CHANCE = 10; // 1/n
    public static Component STARDUST_NAME = mm.deserialize("<gold>별가루");
    public static Material FILLER_ITEM = Material.GRAY_STAINED_GLASS_PANE;
    public static NamespacedKey PATROL_FIREWORK_KEY = new NamespacedKey("darkforest", "patrol");
    public static Component STARPIECE_NAME = mm.deserialize("<light_purple>별조각");
    public static int FILLER_MODEL = 1013145;
    public static Component OBSI_POTION_NAME = mm.deserialize("<light_purple>흑요석 물약");

    public static ItemStack getStardust() {
        ItemStack item = new ItemStack(Material.GLOWSTONE_DUST);
        ItemMeta meta = item.getItemMeta();
        meta.displayName(STARDUST_NAME);
        item.setItemMeta(meta);
        return item;
    }

    public static ItemStack getStarpiece() {
        ItemStack item = new ItemStack(Material.ECHO_SHARD);
        ItemMeta meta = item.getItemMeta();
        meta.displayName(STARPIECE_NAME);
        item.setItemMeta(meta);
        return item;
    }

    public static ItemStack getFiller() { //TODO: change everything to use this
        ItemStack item = new ItemStack(FILLER_ITEM);
        ItemMeta meta = item.getItemMeta();
        meta.displayName(Component.text(""));
        item.setItemMeta(meta);
        return item;
    }

    public static ItemStack getObsipotion() {
        ItemStack item = new ItemStack(Material.POTION);
        PotionMeta meta = (PotionMeta) item.getItemMeta();
        meta.setColor(Color.fromRGB(40, 35, 54)); // #282336
        meta.displayName(OBSI_POTION_NAME);
        meta.addCustomEffect(new PotionEffect(PotionEffectType.FIRE_RESISTANCE, 216000, 0), true);
        item.setItemMeta(meta);
        return item;
    }
}
